export const linkDirectoryCategories = [
	"我的网站",
	"常用网站",
	"资源网站",
	"工具网站",
	"学习网站",
	"文档",
	"AI 工具",
] as const;

export type LinkDirectoryCategory = (typeof linkDirectoryCategories)[number];

export interface LinkDirectoryItem {
	title: string;
	description: string;
	href: string;
	category: LinkDirectoryCategory;
	icon: string;
	external?: boolean;
}

export const linkDirectoryItems: LinkDirectoryItem[] = [
	{
		title: "JingYue 首页",
		description: "记录代码、生活与闪光的片刻",
		href: "/",
		category: "我的网站",
		icon: "material-symbols:home-rounded",
	},
	{
		title: "文章列表",
		description: "按卡片浏览站内全部文章",
		href: "/posts/",
		category: "我的网站",
		icon: "material-symbols:article-rounded",
	},
	{
		title: "文章归档",
		description: "按时间与分类回看内容记录",
		href: "/archive/",
		category: "我的网站",
		icon: "material-symbols:archive-rounded",
	},
	{
		title: "影像相册",
		description: "收藏值得记住的光影片刻",
		href: "/gallery/",
		category: "我的网站",
		icon: "material-symbols:photo-library-rounded",
	},
	{
		title: "友情链接",
		description: "拜访朋友们的小世界",
		href: "/friends/",
		category: "我的网站",
		icon: "material-symbols:group-rounded",
	},
	{
		title: "留言板",
		description: "留下问候与想说的话",
		href: "/guestbook/",
		category: "我的网站",
		icon: "material-symbols:chat-rounded",
	},
	{
		title: "GitHub",
		description: "代码托管、协作与开源项目",
		href: "https://github.com/",
		category: "常用网站",
		icon: "fa7-brands:github",
		external: true,
	},
	{
		title: "哔哩哔哩",
		description: "动画、创作与技术视频社区",
		href: "https://www.bilibili.com/",
		category: "常用网站",
		icon: "fa7-brands:bilibili",
		external: true,
	},
	{
		title: "网易云音乐",
		description: "音乐发现、歌单与收藏",
		href: "https://music.163.com/",
		category: "常用网站",
		icon: "simple-icons:neteasecloudmusic",
		external: true,
	},
	{
		title: "Firefly 源码",
		description: "本站使用的 Astro 博客主题",
		href: "https://github.com/CuteLeaf/Firefly",
		category: "资源网站",
		icon: "fa7-brands:github",
		external: true,
	},
	{
		title: "Firefly 文档",
		description: "主题安装、配置与使用说明",
		href: "https://docs-firefly.cuteleaf.cn/",
		category: "资源网站",
		icon: "material-symbols:menu-book-rounded",
		external: true,
	},
	{
		title: "Astro Integrations",
		description: "查找 Astro 官方与社区集成",
		href: "https://astro.build/integrations/",
		category: "资源网站",
		icon: "material-symbols:extension-rounded",
		external: true,
	},
	{
		title: "Can I Use",
		description: "查询浏览器 Web 特性兼容性",
		href: "https://caniuse.com/",
		category: "工具网站",
		icon: "material-symbols:travel-explore-rounded",
		external: true,
	},
	{
		title: "PageSpeed Insights",
		description: "检测网页性能与核心体验指标",
		href: "https://pagespeed.web.dev/",
		category: "工具网站",
		icon: "material-symbols:speed-rounded",
		external: true,
	},
	{
		title: "Cloudflare Dashboard",
		description: "域名、CDN 与网络安全管理",
		href: "https://dash.cloudflare.com/",
		category: "工具网站",
		icon: "material-symbols:cloud",
		external: true,
	},
	{
		title: "MDN Web Docs",
		description: "权威的 Web 平台技术参考",
		href: "https://developer.mozilla.org/zh-CN/",
		category: "学习网站",
		icon: "material-symbols:school-rounded",
		external: true,
	},
	{
		title: "JavaScript.info",
		description: "现代 JavaScript 系统教程",
		href: "https://zh.javascript.info/",
		category: "学习网站",
		icon: "material-symbols:code-rounded",
		external: true,
	},
	{
		title: "TypeScript Handbook",
		description: "TypeScript 官方语言手册",
		href: "https://www.typescriptlang.org/docs/handbook/intro.html",
		category: "学习网站",
		icon: "material-symbols:data-object-rounded",
		external: true,
	},
	{
		title: "Astro Docs",
		description: "Astro 框架官方文档",
		href: "https://docs.astro.build/zh-cn/",
		category: "文档",
		icon: "material-symbols:rocket-launch-rounded",
		external: true,
	},
	{
		title: "Svelte Docs",
		description: "Svelte 5 官方指南与 API",
		href: "https://svelte.dev/docs/svelte/overview",
		category: "文档",
		icon: "material-symbols:code-rounded",
		external: true,
	},
	{
		title: "Tailwind CSS Docs",
		description: "Tailwind CSS 工具类参考",
		href: "https://tailwindcss.com/docs/installation/using-vite",
		category: "文档",
		icon: "material-symbols:css-rounded",
		external: true,
	},
	{
		title: "ChatGPT",
		description: "OpenAI 通用 AI 助手",
		href: "https://chatgpt.com/",
		category: "AI 工具",
		icon: "simple-icons:openai",
		external: true,
	},
	{
		title: "Claude",
		description: "Anthropic 的 AI 协作助手",
		href: "https://claude.ai/",
		category: "AI 工具",
		icon: "simple-icons:claude",
		external: true,
	},
	{
		title: "Gemini",
		description: "Google 的多模态 AI 助手",
		href: "https://gemini.google.com/",
		category: "AI 工具",
		icon: "material-symbols:auto-awesome-rounded",
		external: true,
	},
];
