export const linkDirectoryCategories = [
	"我的网站",
	"常用网站",
	"资源网站",
	"工具箱",
	"AI 聊天",
	"AI 工具",
	"前端组件库",
	"学习网站",
	"文档",
	"开放 API",
] as const;

export type LinkDirectoryCategory = (typeof linkDirectoryCategories)[number];

export interface LinkDirectoryItem {
	title: string;
	description: string;
	href: string;
	category: LinkDirectoryCategory;
	icon: string;
	iconColor: string;
	iconColorDark?: string;
	external?: boolean;
}

export const linkDirectoryItems: LinkDirectoryItem[] = [
	{
		title: "JingYue 首页",
		description: "记录代码、生活与闪光的片刻",
		href: "/",
		category: "我的网站",
		icon: "material-symbols:home-outline-rounded",
		iconColor: "#4f8ef7",
	},
	{
		title: "文章列表",
		description: "按卡片浏览站内全部文章",
		href: "/posts/",
		category: "我的网站",
		icon: "material-symbols:article-outline-rounded",
		iconColor: "#6366f1",
	},
	{
		title: "文章归档",
		description: "按时间与分类回看内容记录",
		href: "/archive/",
		category: "我的网站",
		icon: "material-symbols:archive-outline-rounded",
		iconColor: "#10b981",
	},
	{
		title: "影像相册",
		description: "收藏值得记住的光影片刻",
		href: "/gallery/",
		category: "我的网站",
		icon: "material-symbols:photo-library-outline-rounded",
		iconColor: "#ec4899",
	},
	{
		title: "友情链接",
		description: "拜访朋友们的小世界",
		href: "/friends/",
		category: "我的网站",
		icon: "material-symbols:group-outline-rounded",
		iconColor: "#f59e0b",
	},
	{
		title: "留言板",
		description: "留下问候与想说的话",
		href: "/guestbook/",
		category: "我的网站",
		icon: "material-symbols:chat-outline-rounded",
		iconColor: "#06b6d4",
	},
	{
		title: "GitHub",
		description: "代码托管、协作与开源项目",
		href: "https://github.com/",
		category: "常用网站",
		icon: "simple-icons:github",
		iconColor: "#181717",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "哔哩哔哩",
		description: "动画、创作与技术视频社区",
		href: "https://www.bilibili.com/",
		category: "常用网站",
		icon: "simple-icons:bilibili",
		iconColor: "#00aeec",
		external: true,
	},
	{
		title: "网易云音乐",
		description: "音乐发现、歌单与收藏",
		href: "https://music.163.com/",
		category: "常用网站",
		icon: "simple-icons:neteasecloudmusic",
		iconColor: "#d43c33",
		external: true,
	},
	{
		title: "Firefly 源码",
		description: "本站使用的 Astro 博客主题",
		href: "https://github.com/CuteLeaf/Firefly",
		category: "资源网站",
		icon: "simple-icons:github",
		iconColor: "#181717",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "Firefly 文档",
		description: "主题安装、配置与使用说明",
		href: "https://docs-firefly.cuteleaf.cn/",
		category: "资源网站",
		icon: "material-symbols:local-fire-department-rounded",
		iconColor: "#ff6b35",
		external: true,
	},
	{
		title: "Astro Integrations",
		description: "查找 Astro 官方与社区集成",
		href: "https://astro.build/integrations/",
		category: "资源网站",
		icon: "simple-icons:astro",
		iconColor: "#bc52ee",
		external: true,
	},
	{
		title: "Can I Use",
		description: "查询浏览器 Web 特性兼容性",
		href: "https://caniuse.com/",
		category: "工具箱",
		icon: "material-symbols:travel-explore-rounded",
		iconColor: "#c75000",
		external: true,
	},
	{
		title: "PageSpeed Insights",
		description: "检测网页性能与核心体验指标",
		href: "https://pagespeed.web.dev/",
		category: "工具箱",
		icon: "simple-icons:pagespeedinsights",
		iconColor: "#4285f4",
		external: true,
	},
	{
		title: "Cloudflare Dashboard",
		description: "域名、CDN 与网络安全管理",
		href: "https://dash.cloudflare.com/",
		category: "工具箱",
		icon: "simple-icons:cloudflare",
		iconColor: "#f38020",
		external: true,
	},
	{
		title: "中科大测速",
		description: "测试当前网络的带宽与延迟",
		href: "https://test.ustc.edu.cn/",
		category: "工具箱",
		icon: "material-symbols:speed-rounded",
		iconColor: "#00a29b",
		external: true,
	},
	{
		title: "ITDOG",
		description: "Ping、网站测速、路由追踪与 DNS 查询",
		href: "https://www.itdog.cn/",
		category: "工具箱",
		icon: "material-symbols:network-check-rounded",
		iconColor: "#2563eb",
		external: true,
	},
	{
		title: "在线图像工具箱",
		description: "在线转换、压缩和裁剪图片",
		href: "https://phototool.cn/",
		category: "工具箱",
		icon: "material-symbols:image-outline-rounded",
		iconColor: "#ef6694",
		external: true,
	},
	{
		title: "OneImage",
		description: "在浏览器内压缩、裁剪和转换图片",
		href: "https://oneimage.co/",
		category: "工具箱",
		icon: "material-symbols:photo-size-select-large-rounded",
		iconColor: "#7c3aed",
		external: true,
	},
	{
		title: "SauceNAO",
		description: "通过图片查找插画等内容的来源",
		href: "https://saucenao.com/",
		category: "工具箱",
		icon: "material-symbols:image-search-rounded",
		iconColor: "#d97706",
		external: true,
	},
	{
		title: "PatorJK",
		description: "生成 ASCII 艺术字的小工具",
		href: "https://patorjk.com/",
		category: "工具箱",
		icon: "material-symbols:text-fields-rounded",
		iconColor: "#64748b",
		external: true,
	},
	{
		title: "豆包",
		description: "对话、写作与日常问答助手",
		href: "https://www.doubao.com/",
		category: "AI 聊天",
		icon: "material-symbols:chat-bubble-outline-rounded",
		iconColor: "#3567e8",
		external: true,
	},
	{
		title: "Grok",
		description: "xAI 的对话式 AI 助手",
		href: "https://grok.com/",
		category: "AI 聊天",
		icon: "material-symbols:auto-awesome-rounded",
		iconColor: "#222222",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "Artificial Analysis",
		description: "比较 AI 模型的能力、速度与价格",
		href: "https://artificialanalysis.ai/",
		category: "AI 工具",
		icon: "material-symbols:analytics-outline-rounded",
		iconColor: "#2563eb",
		external: true,
	},
	{
		title: "AI Arena",
		description: "查看语言模型的社区评测排行榜",
		href: "https://arena.ai/leaderboard",
		category: "AI 工具",
		icon: "material-symbols:leaderboard-rounded",
		iconColor: "#7c3aed",
		external: true,
	},
	{
		title: "ModelScope 魔搭",
		description: "查找、体验与分享开源 AI 模型",
		href: "https://www.modelscope.cn/",
		category: "AI 工具",
		icon: "material-symbols:deployed-code",
		iconColor: "#3269ef",
		external: true,
	},
	{
		title: "PromptPilot",
		description: "火山引擎的提示词优化工具",
		href: "https://promptpilot.volcengine.com/",
		category: "AI 工具",
		icon: "material-symbols:edit-note-rounded",
		iconColor: "#f05a4f",
		external: true,
	},
	{
		title: "Google AI Studio",
		description: "体验 Gemini 模型并制作 AI 原型",
		href: "https://aistudio.google.com/",
		category: "AI 工具",
		icon: "simple-icons:googlegemini",
		iconColor: "#8e75b2",
		external: true,
	},
	{
		title: "Ollama",
		description: "在本地运行和管理开放模型",
		href: "https://ollama.com/",
		category: "AI 工具",
		icon: "material-symbols:memory-rounded",
		iconColor: "#111827",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "Figma",
		description: "在线界面设计与团队协作",
		href: "https://www.figma.com/",
		category: "前端组件库",
		icon: "simple-icons:figma",
		iconColor: "#a259ff",
		external: true,
	},
	{
		title: "shadcn/ui",
		description: "可复制和定制的 Web 界面组件",
		href: "https://ui.shadcn.com/",
		category: "前端组件库",
		icon: "material-symbols:widgets-outline-rounded",
		iconColor: "#111827",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "Uiverse",
		description: "社区分享的按钮、输入框和动效组件",
		href: "https://uiverse.io/",
		category: "前端组件库",
		icon: "material-symbols:animation",
		iconColor: "#7c3aed",
		external: true,
	},
	{
		title: "CodePen",
		description: "浏览和试验 HTML、CSS、JavaScript 示例",
		href: "https://codepen.io/",
		category: "前端组件库",
		icon: "simple-icons:codepen",
		iconColor: "#111827",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "React Bits",
		description: "可复用的 React 动画与界面组件",
		href: "https://www.reactbits.dev/",
		category: "前端组件库",
		icon: "material-symbols:auto-awesome-motion-rounded",
		iconColor: "#4f46e5",
		external: true,
	},
	{
		title: "Iconify",
		description: "搜索和使用开源图标合集",
		href: "https://iconify.design/",
		category: "前端组件库",
		icon: "material-symbols:category-outline-rounded",
		iconColor: "#1769aa",
		external: true,
	},
	{
		title: "MDN Web Docs",
		description: "权威的 Web 平台技术参考",
		href: "https://developer.mozilla.org/zh-CN/",
		category: "学习网站",
		icon: "simple-icons:mdnwebdocs",
		iconColor: "#111111",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "JavaScript.info",
		description: "现代 JavaScript 系统教程",
		href: "https://zh.javascript.info/",
		category: "学习网站",
		icon: "simple-icons:javascript",
		iconColor: "#b38f00",
		iconColorDark: "#f7df1e",
		external: true,
	},
	{
		title: "TypeScript Handbook",
		description: "TypeScript 官方语言手册",
		href: "https://www.typescriptlang.org/docs/handbook/intro.html",
		category: "学习网站",
		icon: "simple-icons:typescript",
		iconColor: "#3178c6",
		external: true,
	},
	{
		title: "力扣 LeetCode",
		description: "算法练习、题解与编程竞赛",
		href: "https://leetcode.cn/",
		category: "学习网站",
		icon: "material-symbols:code-rounded",
		iconColor: "#e59b23",
		external: true,
	},
	{
		title: "牛客网",
		description: "笔试面试题、求职交流与在线练习",
		href: "https://www.nowcoder.com/",
		category: "学习网站",
		icon: "material-symbols:school-outline-rounded",
		iconColor: "#26b97d",
		external: true,
	},
	{
		title: "JavaGuide",
		description: "Java 基础、框架与面试知识整理",
		href: "https://javaguide.cn/",
		category: "学习网站",
		icon: "material-symbols:menu-book-outline-rounded",
		iconColor: "#d97706",
		external: true,
	},
	{
		title: "Astro Docs",
		description: "Astro 框架官方文档",
		href: "https://docs.astro.build/zh-cn/",
		category: "文档",
		icon: "simple-icons:astro",
		iconColor: "#bc52ee",
		external: true,
	},
	{
		title: "Svelte Docs",
		description: "Svelte 5 官方指南与 API",
		href: "https://svelte.dev/docs/svelte/overview",
		category: "文档",
		icon: "simple-icons:svelte",
		iconColor: "#ff3e00",
		external: true,
	},
	{
		title: "Tailwind CSS Docs",
		description: "Tailwind CSS 工具类参考",
		href: "https://tailwindcss.com/docs/installation/using-vite",
		category: "文档",
		icon: "simple-icons:tailwindcss",
		iconColor: "#06b6d4",
		external: true,
	},
	{
		title: "ChatGPT",
		description: "OpenAI 通用 AI 助手",
		href: "https://chatgpt.com/",
		category: "AI 聊天",
		icon: "simple-icons:openai",
		iconColor: "#10a37f",
		external: true,
	},
	{
		title: "Claude",
		description: "Anthropic 的 AI 协作助手",
		href: "https://claude.ai/",
		category: "AI 聊天",
		icon: "simple-icons:claude",
		iconColor: "#d97757",
		external: true,
	},
	{
		title: "Gemini",
		description: "Google 的多模态 AI 助手",
		href: "https://gemini.google.com/",
		category: "AI 聊天",
		icon: "simple-icons:googlegemini",
		iconColor: "#8e75b2",
		external: true,
	},
	{
		title: "高德开放平台",
		description: "地图、定位与路线规划 API",
		href: "https://lbs.amap.com/",
		category: "开放 API",
		icon: "material-symbols:map-outline-rounded",
		iconColor: "#1677ff",
		external: true,
	},
	{
		title: "聚合数据",
		description: "查询和接入多种数据 API",
		href: "https://www.juhe.cn/",
		category: "开放 API",
		icon: "material-symbols:hub",
		iconColor: "#e86735",
		external: true,
	},
	{
		title: "有道翻译开放平台",
		description: "接入多语言文本翻译 API",
		href: "https://ai.youdao.com/",
		category: "开放 API",
		icon: "material-symbols:translate-rounded",
		iconColor: "#d92b2b",
		external: true,
	},
];
