export const linkDirectoryCategories = [
	"我的网站",
	"常用网站",
	"资源网站",
	"工具网站",
	"学习网站",
	"文档",
	"AI 工具",
] as const;

export type LinkDirectoryCategory = (typeof linkDirectoryCategories)[number];

export interface LinkDirectoryItem {
	title: string;
	description: string;
	href: string;
	category: LinkDirectoryCategory;
	icon: string;
	iconColor: string;
	iconColorDark?: string;
	external?: boolean;
}

export const linkDirectoryItems: LinkDirectoryItem[] = [
	{
		title: "JingYue 首页",
		description: "记录代码、生活与闪光的片刻",
		href: "/",
		category: "我的网站",
		icon: "material-symbols:home-outline-rounded",
		iconColor: "#4f8ef7",
	},
	{
		title: "文章列表",
		description: "按卡片浏览站内全部文章",
		href: "/posts/",
		category: "我的网站",
		icon: "material-symbols:article-outline-rounded",
		iconColor: "#6366f1",
	},
	{
		title: "文章归档",
		description: "按时间与分类回看内容记录",
		href: "/archive/",
		category: "我的网站",
		icon: "material-symbols:archive-outline-rounded",
		iconColor: "#10b981",
	},
	{
		title: "影像相册",
		description: "收藏值得记住的光影片刻",
		href: "/gallery/",
		category: "我的网站",
		icon: "material-symbols:photo-library-outline-rounded",
		iconColor: "#ec4899",
	},
	{
		title: "友情链接",
		description: "拜访朋友们的小世界",
		href: "/friends/",
		category: "我的网站",
		icon: "material-symbols:group-outline-rounded",
		iconColor: "#f59e0b",
	},
	{
		title: "留言板",
		description: "留下问候与想说的话",
		href: "/guestbook/",
		category: "我的网站",
		icon: "material-symbols:chat-outline-rounded",
		iconColor: "#06b6d4",
	},
	{
		title: "GitHub",
		description: "代码托管、协作与开源项目",
		href: "https://github.com/",
		category: "常用网站",
		icon: "simple-icons:github",
		iconColor: "#181717",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "哔哩哔哩",
		description: "动画、创作与技术视频社区",
		href: "https://www.bilibili.com/",
		category: "常用网站",
		icon: "simple-icons:bilibili",
		iconColor: "#00aeec",
		external: true,
	},
	{
		title: "网易云音乐",
		description: "音乐发现、歌单与收藏",
		href: "https://music.163.com/",
		category: "常用网站",
		icon: "simple-icons:neteasecloudmusic",
		iconColor: "#d43c33",
		external: true,
	},
	{
		title: "Firefly 源码",
		description: "本站使用的 Astro 博客主题",
		href: "https://github.com/CuteLeaf/Firefly",
		category: "资源网站",
		icon: "simple-icons:github",
		iconColor: "#181717",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "Firefly 文档",
		description: "主题安装、配置与使用说明",
		href: "https://docs-firefly.cuteleaf.cn/",
		category: "资源网站",
		icon: "material-symbols:local-fire-department-rounded",
		iconColor: "#ff6b35",
		external: true,
	},
	{
		title: "Astro Integrations",
		description: "查找 Astro 官方与社区集成",
		href: "https://astro.build/integrations/",
		category: "资源网站",
		icon: "simple-icons:astro",
		iconColor: "#bc52ee",
		external: true,
	},
	{
		title: "Can I Use",
		description: "查询浏览器 Web 特性兼容性",
		href: "https://caniuse.com/",
		category: "工具网站",
		icon: "material-symbols:travel-explore-rounded",
		iconColor: "#c75000",
		external: true,
	},
	{
		title: "PageSpeed Insights",
		description: "检测网页性能与核心体验指标",
		href: "https://pagespeed.web.dev/",
		category: "工具网站",
		icon: "simple-icons:pagespeedinsights",
		iconColor: "#4285f4",
		external: true,
	},
	{
		title: "Cloudflare Dashboard",
		description: "域名、CDN 与网络安全管理",
		href: "https://dash.cloudflare.com/",
		category: "工具网站",
		icon: "simple-icons:cloudflare",
		iconColor: "#f38020",
		external: true,
	},
	{
		title: "MDN Web Docs",
		description: "权威的 Web 平台技术参考",
		href: "https://developer.mozilla.org/zh-CN/",
		category: "学习网站",
		icon: "simple-icons:mdnwebdocs",
		iconColor: "#111111",
		iconColorDark: "#f0f0f0",
		external: true,
	},
	{
		title: "JavaScript.info",
		description: "现代 JavaScript 系统教程",
		href: "https://zh.javascript.info/",
		category: "学习网站",
		icon: "simple-icons:javascript",
		iconColor: "#b38f00",
		iconColorDark: "#f7df1e",
		external: true,
	},
	{
		title: "TypeScript Handbook",
		description: "TypeScript 官方语言手册",
		href: "https://www.typescriptlang.org/docs/handbook/intro.html",
		category: "学习网站",
		icon: "simple-icons:typescript",
		iconColor: "#3178c6",
		external: true,
	},
	{
		title: "Astro Docs",
		description: "Astro 框架官方文档",
		href: "https://docs.astro.build/zh-cn/",
		category: "文档",
		icon: "simple-icons:astro",
		iconColor: "#bc52ee",
		external: true,
	},
	{
		title: "Svelte Docs",
		description: "Svelte 5 官方指南与 API",
		href: "https://svelte.dev/docs/svelte/overview",
		category: "文档",
		icon: "simple-icons:svelte",
		iconColor: "#ff3e00",
		external: true,
	},
	{
		title: "Tailwind CSS Docs",
		description: "Tailwind CSS 工具类参考",
		href: "https://tailwindcss.com/docs/installation/using-vite",
		category: "文档",
		icon: "simple-icons:tailwindcss",
		iconColor: "#06b6d4",
		external: true,
	},
	{
		title: "ChatGPT",
		description: "OpenAI 通用 AI 助手",
		href: "https://chatgpt.com/",
		category: "AI 工具",
		icon: "simple-icons:openai",
		iconColor: "#10a37f",
		external: true,
	},
	{
		title: "Claude",
		description: "Anthropic 的 AI 协作助手",
		href: "https://claude.ai/",
		category: "AI 工具",
		icon: "simple-icons:claude",
		iconColor: "#d97757",
		external: true,
	},
	{
		title: "Gemini",
		description: "Google 的多模态 AI 助手",
		href: "https://gemini.google.com/",
		category: "AI 工具",
		icon: "simple-icons:googlegemini",
		iconColor: "#8e75b2",
		external: true,
	},
];
