export const personalScheduleConfig = {
	events: [
		{
			date: "09-17",
			time: "19:30",
			title: "整理博客更新清单",
			detail: "把这一周值得留下的变化写进记录。",
		},
		{
			date: "09-20",
			time: "20:00",
			title: "相册夜间整理",
			detail: "挑选几张喜欢的照片，留给未来慢慢看。",
		},
		{
			date: "10-04",
			time: "10:00",
			title: "Duro 的生日茶会",
			detail: "给小伙伴们准备一份轻轻的秋日祝福。",
		},
	],
	anniversaries: [
		{ title: "新年的第一束光", kind: "节日", date: "01-01", tone: "rose" },
		{ title: "菲比啾比纪念日", kind: "伙伴", date: "02-14", tone: "gold" },
		{ title: "博客启程纪念日", kind: "博客", date: "07-15", tone: "rose" },
		{ title: "鲸鱼娘的生日", kind: "伙伴", date: "09-17", tone: "gold" },
		{ title: "Duro 的生日", kind: "伙伴", date: "10-04", tone: "rose" },
		{ title: "咕咕嘎嘎纪念日", kind: "伙伴", date: "12-30", tone: "gold" },
	],
} as const;

export const personalBillsConfig = {
	entries: [
		{
			date: "2026-09-17",
			time: "19:20",
			category: "餐饮",
			title: "晚饭",
			type: "expense",
			amount: 15.9,
			icon: "material-symbols:restaurant-outline-rounded",
		},
		{
			date: "2026-09-17",
			time: "16:27",
			category: "交通",
			title: "骑行",
			type: "expense",
			amount: 2,
			icon: "material-symbols:directions-bike-outline-rounded",
		},
		{
			date: "2026-09-17",
			time: "10:07",
			category: "餐饮",
			title: "午饭",
			type: "expense",
			amount: 12.4,
			icon: "material-symbols:restaurant-outline-rounded",
		},
		{
			date: "2026-09-16",
			time: "23:02",
			category: "生活",
			title: "洗衣",
			type: "expense",
			amount: 3,
			icon: "material-symbols:local-laundry-service-outline-rounded",
		},
		{
			date: "2026-09-16",
			time: "10:37",
			category: "生活",
			title: "水卡充值",
			type: "expense",
			amount: 20,
			icon: "material-symbols:water-drop-outline",
		},
		{
			date: "2026-09-16",
			time: "10:21",
			category: "餐饮",
			title: "午饭",
			type: "expense",
			amount: 14.38,
			icon: "material-symbols:restaurant-outline-rounded",
		},
		{
			date: "2026-09-13",
			time: "18:40",
			category: "博客",
			title: "域名续费",
			type: "expense",
			amount: 69,
			icon: "material-symbols:language",
		},
		{
			date: "2026-09-13",
			time: "09:30",
			category: "创作",
			title: "稿费",
			type: "income",
			amount: 300,
			icon: "material-symbols:edit-note-rounded",
		},
		{
			date: "2026-09-10",
			time: "15:10",
			category: "学习",
			title: "书籍",
			type: "expense",
			amount: 42.8,
			icon: "material-symbols:menu-book-outline-rounded",
		},
		{
			date: "2026-09-08",
			time: "17:45",
			category: "生活",
			title: "日用品",
			type: "expense",
			amount: 58.2,
			icon: "material-symbols:shopping-bag-outline-rounded",
		},
		{
			date: "2026-09-04",
			time: "08:16",
			category: "交通",
			title: "通勤",
			type: "expense",
			amount: 12,
			icon: "material-symbols:directions-bus-outline-rounded",
		},
		{
			date: "2026-09-01",
			time: "00:03",
			category: "博客",
			title: "云服务",
			type: "expense",
			amount: 25,
			icon: "material-symbols:cloud-outline",
		},
		{
			date: "2026-08-26",
			time: "14:10",
			category: "创作",
			title: "项目结算",
			type: "income",
			amount: 520,
			icon: "material-symbols:payments-outline-rounded",
		},
		{
			date: "2026-08-21",
			time: "20:30",
			category: "娱乐",
			title: "电影",
			type: "expense",
			amount: 45,
			icon: "material-symbols:movie-outline-rounded",
		},
		{
			date: "2026-08-14",
			time: "12:00",
			category: "餐饮",
			title: "聚餐",
			type: "expense",
			amount: 86,
			icon: "material-symbols:restaurant-outline-rounded",
		},
		{
			date: "2026-08-06",
			time: "09:20",
			category: "学习",
			title: "课程",
			type: "expense",
			amount: 120,
			icon: "material-symbols:school-outline-rounded",
		},
	],
} as const;
