import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(projectRoot, "src/config/recordSync.ts");
const biomePath = resolve(projectRoot, "node_modules/@biomejs/biome/bin/biome");

function runGit(args) {
	try {
		return execFileSync("git", args, {
			cwd: projectRoot,
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		}).trim();
	} catch {
		return "";
	}
}

function listCommits() {
	const output = runGit([
		"log",
		"--date=iso-strict",
		"--format=%h%x1f%p%x1f%ad%x1f%s",
		"--max-count=5000",
	]);
	return output
		.split("\n")
		.map((line) => line.split("\x1f"))
		.filter(([hash, , date, subject]) => hash && date && subject)
		.map(([hash, parents, date, subject]) => ({
			hash,
			parents: parents.split(" ").filter(Boolean),
			date,
			dateKey: date.slice(0, 10),
			time: date.slice(11, 16),
			subject,
		}));
}

const commits = listCommits();
const newestAllowed = new Date();
newestAllowed.setUTCDate(newestAllowed.getUTCDate() - 364);
const activityStart = newestAllowed.toISOString().slice(0, 10);
const activityByDate = {};

for (const commit of commits) {
	if (commit.dateKey < activityStart) continue;
	activityByDate[commit.dateKey] = (activityByDate[commit.dateKey] ?? 0) + 1;
}

// Keep curated history in recordConfig.ts, then append every newer conventional
// commit as a lightweight entry so the changelog stays current after each build.
const changelogAnchor = "2026-08-30";
const typeMap = {
	feat: "feature",
	fix: "fix",
	perf: "optimize",
	refactor: "optimize",
	style: "optimize",
	chore: "optimize",
	docs: "optimize",
};
const changelogCommits = commits
	.filter((commit) => commit.dateKey > changelogAnchor)
	.map((commit) => {
		const match = commit.subject.match(/^([a-z]+)(?:\([^)]*\))?!?:\s*(.+)$/i);
		if (!match) return null;
		const [, rawType, title] = match;
		const type = typeMap[rawType.toLowerCase()] || "optimize";
		return {
			...commit,
			title,
			type,
		};
	})
	.filter(Boolean);
const changelogHashes = new Set(changelogCommits.map((commit) => commit.hash));
const generatedEntries = changelogCommits.map((commit) => {
	return {
		version: `git-${commit.hash}`,
		date: commit.dateKey,
		time: commit.date.slice(11, 16),
		type: commit.type,
		title: commit.title,
		summary: `提交 ${commit.hash}：${commit.title}`,
		changes: ["由 Git 提交自动记录，详细改动请查看对应提交。"],
		related: commit.parents
			.filter((parent) => changelogHashes.has(parent))
			.map((parent) => `git-${parent}`),
	};
});

const content =
	"// Generated by scripts/sync-records.mjs. Do not edit by hand.\n" +
	`export const gitActivityByDate: Record<string, number> = ${JSON.stringify(activityByDate, null, "\t")};\n\n` +
	`export const generatedChangelogEntries: Array<{ version: string; date: string; time: string; type: "feature" | "fix" | "optimize" | "remove"; title: string; summary: string; changes: string[]; related: string[] }> = ${JSON.stringify(generatedEntries, null, "\t")};\n`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, "utf8");
try {
	execFileSync(process.execPath, [biomePath, "format", "--write", outputPath], {
		cwd: projectRoot,
		stdio: "ignore",
	});
} catch {
	// Formatting is optional when the sync script runs before dependencies exist.
}
console.log(
	`[sync-records] ${Object.keys(activityByDate).length} activity days`,
);
