import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(projectRoot, "src/config/recordSync.ts");
const recordConfigPath = resolve(projectRoot, "src/config/recordConfig.ts");
const biomePath = resolve(projectRoot, "node_modules/@biomejs/biome/bin/biome");

function runGit(args) {
	try {
		return execFileSync("git", args, {
			cwd: projectRoot,
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		}).trim();
	} catch {
		return "";
	}
}

function classify(subject) {
	const prefix = subject
		.match(/^([a-z]+)(?:\([^)]*\))?:\s*/i)?.[1]
		?.toLowerCase();
	if (prefix === "feat" || prefix === "feature") return "feature";
	if (prefix === "fix" || prefix === "bugfix") return "fix";
	if (prefix === "remove" || prefix === "revert") return "remove";
	return "optimize";
}

function cleanSubject(subject) {
	return subject.replace(/^[a-z]+(?:\([^)]*\))?:\s*/i, "").trim() || subject;
}

function getBaselineDate() {
	try {
		const source = readFileSync(recordConfigPath, "utf8");
		const dates = [
			...source.matchAll(/date:\s*["'](\d{4}-\d{2}-\d{2})["']/g),
		].map((match) => match[1]);
		return dates.sort().at(-1) ?? "";
	} catch {
		return "";
	}
}

function listCommits() {
	const output = runGit([
		"log",
		"--date=iso-strict",
		"--format=%h%x1f%ad%x1f%s",
		"--max-count=1000",
	]);
	return output
		.split("\n")
		.map((line) => line.split("\x1f"))
		.filter(([hash, date, subject]) => hash && date && subject)
		.map(([hash, date, subject]) => ({
			hash,
			date,
			dateKey: date.slice(0, 10),
			time: date.slice(11, 16),
			subject,
		}));
}

function changedFiles(hash) {
	const output = runGit([
		"show",
		"--format=",
		"--name-only",
		"--no-renames",
		hash,
	]);
	return output
		.split("\n")
		.map((file) => file.trim())
		.filter(Boolean)
		.slice(0, 5);
}

const commits = listCommits();
const baselineDate = getBaselineDate();
const newestAllowed = new Date();
newestAllowed.setUTCDate(newestAllowed.getUTCDate() - 364);
const activityStart = newestAllowed.toISOString().slice(0, 10);
const activityByDate = {};

for (const commit of commits) {
	if (commit.dateKey < activityStart) continue;
	activityByDate[commit.dateKey] = (activityByDate[commit.dateKey] ?? 0) + 1;
}

const generatedEntries = commits
	.filter((commit) => !baselineDate || commit.dateKey > baselineDate)
	.map((commit) => {
		const title = cleanSubject(commit.subject);
		const files = changedFiles(commit.hash);
		return {
			version: `commit-${commit.dateKey.replaceAll("-", "")}-${commit.time.replace(":", "")}`,
			date: commit.dateKey,
			time: commit.time,
			type: classify(commit.subject),
			title,
			summary: `GitHub 同步记录：${title}`,
			changes: [
				"提交已同步到 GitHub。",
				...(files.length ? [`涉及 ${files.join("、")}。`] : []),
			],
		};
	});

const content =
	"// Generated by scripts/sync-records.mjs. Do not edit by hand.\n" +
	`export const gitActivityByDate: Record<string, number> = ${JSON.stringify(activityByDate, null, "\t")};\n\n` +
	`export const generatedChangelogEntries = ${JSON.stringify(generatedEntries, null, "\t")} as const;\n`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, "utf8");
try {
	execFileSync(process.execPath, [biomePath, "format", "--write", outputPath], {
		cwd: projectRoot,
		stdio: "ignore",
	});
} catch {
	// Formatting is optional when the sync script runs before dependencies exist.
}
console.log(
	`[sync-records] ${Object.keys(activityByDate).length} activity days, ${generatedEntries.length} Git commits in changelog`,
);
