import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(projectRoot, "src/config/recordSync.ts");
const biomePath = resolve(projectRoot, "node_modules/@biomejs/biome/bin/biome");

function runGit(args) {
	try {
		return execFileSync("git", args, {
			cwd: projectRoot,
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		}).trim();
	} catch {
		return "";
	}
}

function listCommits() {
	const output = runGit([
		"log",
		"--date=iso-strict",
		"--format=%h%x1f%ad%x1f%s",
		"--max-count=5000",
	]);
	return output
		.split("\n")
		.map((line) => line.split("\x1f"))
		.filter(([hash, date, subject]) => hash && date && subject)
		.map(([hash, date, subject]) => ({
			hash,
			date,
			dateKey: date.slice(0, 10),
			time: date.slice(11, 16),
			subject,
		}));
}

const commits = listCommits();
const newestAllowed = new Date();
newestAllowed.setUTCDate(newestAllowed.getUTCDate() - 364);
const activityStart = newestAllowed.toISOString().slice(0, 10);
const activityByDate = {};

for (const commit of commits) {
	if (commit.dateKey < activityStart) continue;
	activityByDate[commit.dateKey] = (activityByDate[commit.dateKey] ?? 0) + 1;
}

// Git history only feeds the contribution graph. Changelog entries are curated
// in src/config/recordConfig.ts and are never generated from push activity.
const generatedEntries = [];

const content =
	"// Generated by scripts/sync-records.mjs. Do not edit by hand.\n" +
	`export const gitActivityByDate: Record<string, number> = ${JSON.stringify(activityByDate, null, "\t")};\n\n` +
	`export const generatedChangelogEntries: Array<{ version: string; date: string; time: string; type: "feature" | "fix" | "optimize" | "remove"; title: string; summary: string; changes: string[] }> = ${JSON.stringify(generatedEntries, null, "\t")};\n`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, "utf8");
try {
	execFileSync(process.execPath, [biomePath, "format", "--write", outputPath], {
		cwd: projectRoot,
		stdio: "ignore",
	});
} catch {
	// Formatting is optional when the sync script runs before dependencies exist.
}
console.log(
	`[sync-records] ${Object.keys(activityByDate).length} activity days`,
);
